# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    increment_version_code
    gradle(task: "clean assembleRelease")
  end

  desc "Beta a new version to the Google Play"
  lane :beta do
    increment_version_code
    gradle(task: "clean bundleRelease")
    supply(track: "beta", track_promote_to: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code
    gradle(task: "clean bundleRelease")
    upload_to_play_store
  end
end

after_all do |lane|
  slack(
    channel: "#dev",
    message: "FastLane success",
    slack_url: ENV['WEBHOOK_URL']
  )
end